### ISSUE TITLE
Need Touch Event gesture

### ISSUE THREAD

**Issue by sohamb1390** [EvanCooper9/swift-week-view#1]
Hey,
It's a fabulous control and It really has some cool capabilities in order to build a complete event based calendar control. One thing I really need in my project is to touch on any events and do some action. Could you please guide me how would I do it?

**Comment by EvanCooper9** [comment]
@sohamb1390 
I'm working on this already, but am not ready to push to the repository. I plan to add a general touch-listener as a delegate function, but haven't gotten around to completing it. I can try to get it done soon.

To implement yourself, you should be able to use the `weekViewStylerEventView` method defined in the `WeekViewStyler` protocol. Perhaps try this:
1. Implement the protocol and method above
2. Create the view for the given event, and add a touch-listener to it
3. Return the view to the protocol method

**Comment by sohamb1390** [comment]
Hi Evan,
I tried what you have suggested like this:

1. I have implemented the method `weekViewStylerEventView` and inside it, I am returning views for individual events.

2. I have added Tap gesture into each view:
`let tapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(onTapEventView(_:)))`
`eventView.addGestureRecognizer(tapGestureRecognizer)`

3. I implemented the gesture method inside my viewController class:
`@objc func onTapEventView(_ gesture: UIGestureRecognizer) { print("tapped") }`

But unfortunately it's not triggering this method whenever I am touching any event view.

Any idea?

**Comment by EvanCooper9** [comment]
I think either one of the superviews of the `eventView` is highjacking the touch, or more likely its related to something in my logic for the scrollview behind it all. I'm having a look now.

**Comment by EvanCooper9** [comment]
@sohamb1390 
Check the latest commit. I've added the ability to respond to touches.

1. The signature of  `weekViewStylerEventView` has changed. It's only the return type that has changed from `UIView` to `WeekViewEventView`.
2.  Conform to the `WeekViewDelegate` protocol and implement its only method: `weekViewDidClickOnEvent`.
3. Assign the delegate property of your `weekView` instance to the relevant class.
4. In the `WeekView` constructor, ensure to add the parameter `respondsToInteraction` and set it to `true`

Then you're good to go!

Let me know of any bugs that you find, it's a little hacky right now but it should work but I haven't done too much testing.
Thanks!

**Comment by sohamb1390** [comment]
Thanks a Lot Evan!
You saved my day. It's working like a charm, please do let me know when you are going to provide a permanent fix in a new release.

Thanks Again!
