### ISSUE TITLE
No such module 'TimelineCollectionView'

### ISSUE THREAD

**Issue by jagadishyaragarla1** [EvanCooper9/swift-week-view#12]
I
<img width="1236" alt="screen shot 2019-02-28 at 10 26 37 pm" src="https://user-images.githubusercontent.com/41121263/53583650-02db9400-3ba8-11e9-9a9b-aafe93937e80.png">
 had download your zip code and when I run it in the Xcode it show error like No Such Module'TimelineCollectionView' and also have frameworks too in the project but also show like this error

**Comment by meshileya** [comment]
You can try to delete the Module while you download the TimelineCollectionView from https://github.com/EvanCooper9/TimelineCollectionView/tree/master/TimelineCollectionView , then you move the folder into your project.

**Comment by EvanCooper9** [comment]
FIxed
