### ISSUE TITLE
Swift Week View with JSON

### ISSUE THREAD

**Issue by Ivy-thu** [EvanCooper9/swift-week-view#16]
Dear Evan,

Hello. Nice to meet you here.

I would like to create one small app. I want to show the events from JSON. Each event will have its **specific date**, starting time, ending time and other details. I am quite stuck in the half way to integrate this to my small app.

When I add the code to weekViewGenerateEvents function, it shows same task on all the same date.

Can you please let's me know how should I proceed it? If you have some sample app, it will be great. Thanks in advance.

Cheers!

**Comment by EvanCooper9** [comment]
Sample app has always been available
