### ISSUE TITLE
5.3 compiler does not like TimeLineCollectionView.framework

### ISSUE THREAD

**Issue by perbrondum** [EvanCooper9/swift-week-view#18]
/...swift-week-view-master/Source/Views/WeekView.swift:12:8: Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.3 compiler: /...swiftweek/swiftweek/TimelineCollectionView.framework/Modules/TimelineCollectionView.swiftmodule/x86_64.swiftmodule

**Comment by EvanCooper9** [comment]
https://github.com/EvanCooper9/swift-week-view/tree/spm-support#swift-package-manager

**Comment by perbrondum** [comment]
Awesome Thanks!
