### ISSUE TITLE
Using Firebase with your code

### ISSUE THREAD

**Issue by ludovicoloreti** [EvanCooper9/swift-week-view#4]
Hello, 
It's about 10 days I'm trying to figure out how to edit a little part of your code only to be able to use it with Firebase.
Firebase it's downloading all events already added in your way (`WeekViewEvent`) but the problem is the function `weekViewGenerateEvents()`.
I really dunno how to solve it, I know the problem is the async and the sync. But really dunno how to solve.
Could you please help me just a little bit?

How can I use it synchronously? Thank you very much.
Best, best regards!

**Comment by EvanCooper9** [comment]
@ludovicoloreti could you post the code that you're using within `weekViewGenerateEvents()`?

**Comment by ludovicoloreti** [comment]
yes of course! Thank you for your fast reply!
`func weekViewGenerateEvents(_ weekView: WeekView, date: DateInRegion) -> [WeekViewEvent] {
        let db = dbRef.child("items").child(codiceUtente)
        db.observe(.value, with: { (snapshot) in
            guard let itemData = snapshot.children.allObjects as? [DataSnapshot] else {return}
            if (snapshot.exists() == false) {
                Utils.showAlert(title: "Nessun Dato", msg: "Nessun dato presente nel Database di Firebase!", in: self)
                return
            } else {
                for child in itemData {
                    guard let eventName = child.childSnapshot(forPath: "eventName").value as? String else {
                        Utils.showAlert(title: "Erroe campo eventName", msg: "Errore nel campo NOME_EVENTO (titolo evento), contattare amministratore!", in: self)
                        return
                    }
                    guard let startDate = child.childSnapshot(forPath: "startDate").value as? String else {
                        Utils.showAlert(title: "Erroe campo startDate", msg: "Errore nel campo DATA_INIZIO, contattare amministratore!", in: self)
                        return
                    }
                    guard let endDate = child.childSnapshot(forPath: "endDate").value as? String else {
                        Utils.showAlert(title: "Erroe campo endDate", msg: "Errore nel campo DATA_FINE, contattare amministratore!", in: self)
                        return
                    }
                    let initDate = DateInRegion(string: startDate, format: .custom("dd-MM-yyyy HH:mm"), fromRegion: self.regionRome)!
                    let finalDate = DateInRegion(string: endDate, format: .custom("dd-MM-yyyy HH:mm"), fromRegion: self.regionRome)!
                    let item: WeekViewEvent = WeekViewEvent(title: eventName, start: initDate, end: finalDate)
                    if date.day == initDate.day && date.day == finalDate.day {
                        self.items.append(item)
                    }
                    DispatchQueue.main.async {
                        print("CIAO",self.items)
//                        return self.items
                    }
                }
            }
        })
//        print("itemsssss",date.day ,"\n\n\n\n\n\n\n",items,"\n\n\n\n\n\n\n\n end itemszzz")
        return items
    }`

The problem is (maybe the code is also not correct in the end where I want to print the array of items declared in the top of the `viewcontrolller` class like this: `var items = [WeekViewEvent]()`) my code is fired in different time into the `weekViewGenerateEvents()` function...

However the prob

**Comment by EvanCooper9** [comment]
Ok so the problem: 
- `weeViewGenerateEvents` runs synchronously
- Firebase code runs asynchronously

This means that `weeViewGenerateEvents` has already returned before the firebase code has completed fetching your results. I'm working on a fix right now.

**Comment by ludovicoloreti** [comment]
God save @EvanCooper9 
Thousands of thanks!

**Comment by EvanCooper9** [comment]
I noticed also that for each event you're creating, you're returning that event. You should create all `WeekViewEvents`, store them in an array, and return that array.

I added `eventCompletion: @escaping ([WeekViewEvent]) -> Void` to the `weekViewGenerateEvents` method. It's not perfect but it will work for you. Once you've put all events for a single day in an array, you can do `eventCompletion(events)` to send them to the `WeekView`.

**Comment by ludovicoloreti** [comment]
So you are saying that I can get my data from firebase inside your `weekViewGenerateEvents()`, and instead of the returning statement (you talked before that I've used it, (now obviusly wrong)) I can literally append items to an array (like this array outside every functions: `var items = [WeekViewEvent]()`), then always inside your function I can compare all the array with your currently `date` (the input in your function, type `DateInRegion`) and add to something like a new `event` array with all the events in that date, and it will redo all of this I just said for every day in the printed `WeekView`. 

Is it correct? 

_(and I add that maybe I could put my firebase data get outside that function because the array with events is always the same, but obviusly I dont know how because it's async so I'm not able to do something like this, only the first part I wrote before this brackets)_

**Comment by EvanCooper9** [comment]
@ludovicoloreti  You really have two options, so you can do one of the following.

Given that `items` is of type `[WeekViewEvent]`:
1. Fetch all your data from Firebase __outside__ of `weekViewGenerateEvents()`, then return the ones that match with `date` within the function like so: `return items`.
2. Fetch all events that are related to `date` __within__ `weekViewGenerateEvents()`, and use the asynchronous callback to pass these events to the `WeekView` like so : `eventCompletion(items)`, and then `return []`.

**Comment by ludovicoloreti** [comment]
Last question:
Is it possible to add events directly without using `weekViewGenerateEvents` ? 
In that way it will be simple because I will add events async and only one time, every event will be added. Sorry and thanks

**Comment by EvanCooper9** [comment]
Hey, is this still an issue? If so, have a look at the newest update
