### ISSUE TITLE
Creating Events asynchronously

### ISSUE THREAD

**Issue by robban112** [EvanCooper9/swift-week-view#6]
Hi!

I'm creating an app where the users can create events from the app. However, I'm having trouble with refreshing the weekView or using the eventCompletion in weekViewGenerateEvents.
How am I supposed to create new events?

Thanks!

**Comment by EvanCooper9** [comment]
Hey @robban112,
I'm working on implementing a collection view as the base layer which would make this easy for you. I'll have a method where you can update the data for a specific day of the week.

**Comment by robban112** [comment]
Thanks for the answer. Sounds good! Do you have any idea when this will be finished?

**Comment by EvanCooper9** [comment]
Should be easier now with `2d8c5d9`
